language: python

# This (sudo: false) is needed to "run on container-based infrastructure" on
# which cache: is available
# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

cache: pip

before_install:
  - pip install -r requirements.txt
  - pip install flake8

before_script:
  - flake8 -v .

script:
  - python setup.py test -t test/unit -v
  - python setup.py sdist install
  - pip install dist/*.tar.gz
  - scc version
  - scc -h
